version: '3.8'
services:
    db:
        container_name: postgres_container
        image: postgres:14.1-alpine
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test_db
        ports:
            - "5432:5432"
        volumes:
            - ./tmp/db:/var/lib/postgresql/data

